slice_name: Top products by units sold
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params: '{"viz_type": "echarts_timeseries_bar", "x_axis": "product_name", "metrics":
  ["units_sold"], "groupby": [], "row_limit": 15, "orderby": [["units_sold", false]],
  "order_desc": true, "adhoc_filters": []}'
query_context: null
cache_timeout: null
uuid: 33333333-3333-4333-8333-000000000002
version: 1.0.0
dataset_uuid: 22222222-2222-4222-8222-000000000002
is_managed_externally: false
external_url: null
