ALTER TABLE public.transactions REPLICA IDENTITY FULL;
ALTER TABLE public.shippings REPLICA IDENTITY FULL;
ALTER TABLE public.users REPLICA IDENTITY FULL;
ALTER TABLE public.products REPLICA IDENTITY FULL;
ALTER TABLE public.payments REPLICA IDENTITY FULL;